### PR TITLE
Too late! I did more!

### PR DESCRIPTION
**Pull request by MiningTcup**
In addition to preventing spawn killing, you can now prevent pet deaths!

### CODE REVIEW

**Comment by MiningTcup** [comment]
Looks like I forgot to update the version number.

**Comment by MiningTcup** [comment]
This is getting really complicated and I wouldn't be surprised if it's broken in some way. The testing I'm doing is just default settings.

**Comment by MiningTcup** [comment]
btw I just didn't know the pull request automatically updates when I make a push. oh well!

**Comment by LukeOnuke** [comment]
damn lmao

**Comment by LukeOnuke** [comment]
you realy pump out code at ludicrous speeds

**Comment by MiningTcup** [comment]
It's Thanksgiving break... I've made about five other semi-function plugins in the last few days. Take your time, though.

**Comment by MiningTcup** [comment]
You should link the Modrinth page oh Github somewhere, I think maybe there's a website info thing.

**Pull request merged**
